var liliwerface = document.getElementById("liliwerface");
liliwerface.addEventListener("click", switchLiliwerImage);
var liliwerImage = 0;
var songDisplay = 0;

function switchLiliwerImage() {
  if (liliwerImage == 0) {
    liliwerface.innerHTML = "<img id='liliwerart' src='liliwer-baby-image.png'>";
    liliwerImage = 1;
  } else {
    liliwerface.innerHTML = "<img id='liliwerfaceimage' src='liliwer-is-a-peculiar-non-playable-character-exhibit-a.jpg'>";
    liliwerImage = 0;
  }
}

function displaySongs() {
  if (songDisplay == 0) {
    document.getElementById("songsdiv").innerHTML = "<p class='songtitles' id='lapstitle'>LAPS</p> <img class='art' id='lapsart' src='laps-art.jpg'> <br><br><br> <audio controls class='audiocontrols' id='lapsaudio'> <source src='LAPS (OFFICAL RELEASE) - 9_17_23, 6.32 PM.mp3' type='audio/mpeg'> Your browser does not support the audio element. </audio> <div class='rating'><span class='emptystar' id='lapsfifthstar'>☆</span><span class='emptystar' id='lapsfourthstar'>☆</span><span class='emptystar' id='lapsthirdstar'>☆</span><span class='emptystar' id='lapssecondstar'>☆</span><span class='emptystar' id='lapsfirststar'>☆</span></div> <p class='songtitles' id='unstoppabletitle'>UNSTOPPABLE</p> <img class='art' id='unstoppableart' src='unstoppable-art.jpg'> <br><br><br> <audio controls class='audiocontrols' id='unstoppableaudio'> <source src='UNSTOPPABLE (prod cadence x k1bo x surfufoolin).mp3' type='audio/mpeg'> Your browser does not support the audio element. </audio> <div class='rating'><span class='emptystar' id='unstoppablefifthstar'>☆</span><span class='emptystar'id='unstoppablefourthstar'>☆</span><span class='emptystar' id='unstoppablethirdstar'>☆</span><span class='emptystar' id='unstoppablesecondstar'>☆</span><span class='emptystar' id='unstoppablefirststar'>☆</span></div> <p class='songtitles' id='stolemyhearttitle'>STOLE MY HEART</p> <img class='art' id='stolemyheartart' src='stole-my-heart-art.jpg'> <br><br><br> <audio controls class='audiocontrols' id='stolemyheartaudio'> <source src='STOLE MY HEART.mp3' type='audio/mpeg'> Your browser does not support the audio element. </audio> <div class='rating'><span class='emptystar' id='stolemyheartfifthstar'>☆</span><span class='emptystar' id='stolemyheartfourthstar'>☆</span><span class='emptystar' id='stolemyheartthirdstar'>☆</span><span class='emptystar' id='stolemyheartsecondstar'>☆</span><span class='emptystar' id='stolemyheartfirststar'>☆</span></div> <p class='songtitles' id='intheshadowstitle'>IN THE SHADOWS</p> <img class='art' id='intheshadowsart' src='in-the-shadows-art.jpg'> <br><br><br> <audio controls class='audiocontrols' id='intheshadowsaudio'> <source src='IN THE SHADOWS (prod. shanmuga + jang0).mp3' type='audio/mpeg'> Your browser does not support the audio element. </audio> <div class='rating'><span class='emptystar' id='intheshadowsfifthstar'>☆</span><span class='emptystar' id='intheshadowsfourthstar'>☆</span><span class='emptystar' id='intheshadowsthirdstar'>☆</span><span class='emptystar' id='intheshadowssecondstar'>☆</span><span class='emptystar' id='intheshadowsfirststar'>☆</span></div> <p class='songtitles' id='masktitle'>MASK</p> <img class='art' id='maskart' src='mask-art.jpg'> <br><br><br> <audio controls class='audiocontrols' id='maskaudio'> <source src='MASK.mp3' type='audio/mpeg'> Your browser does not support the audio element. </audio> <div class='rating'><span class='emptystar' id='maskfifthstar'>☆</span><span class='emptystar' id='maskfourthstar'>☆</span><span class='emptystar' id='maskthirdstar'>☆</span><span class='emptystar' id='masksecondstar'>☆</span><span class='emptystar' id='maskfirststar'>☆</span></div> <p class='songtitles' id='moneyainttheanswertitle'>MONEY AIN'T THE ANSWER</p> <img class='art' id='moneyainttheanswerart' src='money-aint-the-answer-art.jpg'> <br><br><br> <audio controls class='audiocontrols' id='moneyainttheansweraudio'> <source src='money-aint-the-answer.mp3' type='audio/mpeg'> Your browser does not support the audio element. </audio> <div class='rating'><span class='emptystar' id='moneyainttheanswerfifthstar'>☆</span><span class='emptystar' id='moneyainttheanswerfourthstar'>☆</span><span class='emptystar' id='moneyainttheanswerthirdstar'>☆</span><span class='emptystar' id='moneyainttheanswersecondstar'>☆</span><span class='emptystar' id='moneyainttheanswerfirststar'>☆</span></div> <p class='songtitles' id='fakefriendstitle'>FAKE FRIENDS</p> <img class='art' id='fakefriendsart' src='artworks-Iia3ffv1dKQElv0Q-AnNNHg-t200x200.jpg'> <br><br><br> <audio controls class='audiocontrols' id='fakefriendsaudio'> <source src='FAKE FRIENDS (prod. THERSX).mp3' type='audio/mpeg'> Your browser does not support the audio element. </audio> <div class='rating'><span class='emptystar' id='fakefriendsfifthstar'>☆</span><span class='emptystar' id='fakefriendsfourthstar'>☆</span><span class='emptystar' id='fakefriendsthirdstar'>☆</span><span class='emptystar' id='fakefriendssecondstar'>☆</span><span class='emptystar' id='fakefriendsfirststar'>☆</span></div>";
    document.getElementById("songsheader").innerText = "Hide Liliwer's Songs";
    songDisplay = 1;
    var stars = document.getElementsByClassName("rating");
    for (var i = 0; i < stars.length; i++) {
      stars[i].addEventListener("click", addRating);
    }
  } else {
    document.getElementById('songsdiv').innerHTML = "";
    document.getElementById("songsheader").innerText = "View Liliwer's Songs";
    songDisplay = 0;
  }
}

function addRating() {
  console.log("ok");
  var clickedStar = event.target;
  starId = clickedStar.getAttribute("id");
  var lapsFirstStar = document.getElementById("lapsfirststar");
  var lapsSecondStar = document.getElementById("lapssecondstar");
  var lapsThirdStar = document.getElementById("lapsthirdstar");
  var lapsFourthStar = document.getElementById("lapsfourthstar");
  var lapsFifthStar = document.getElementById("lapsfifthstar");
  var unstoppableFirstStar = document.getElementById("unstoppablefirststar");
  var unstoppableSecondStar = document.getElementById("unstoppablesecondstar");
  var unstoppableThirdStar = document.getElementById("unstoppablethirdstar");
  var unstoppableFourthStar = document.getElementById("unstoppablefourthstar");
  var unstoppableFifthStar = document.getElementById("unstoppablefifthstar");
  var stolemyheartFirstStar = document.getElementById("stolemyheartfirststar");
  var stolemyheartSecondStar = document.getElementById("stolemyheartsecondstar");
  var stolemyheartThirdStar = document.getElementById("stolemyheartthirdstar");
  var stolemyheartFourthStar = document.getElementById("stolemyheartfourthstar");
  var stolemyheartFifthStar = document.getElementById("stolemyheartfifthstar");
  var intheshadowsFirstStar = document.getElementById("intheshadowsfirststar");
  var intheshadowsSecondStar = document.getElementById("intheshadowssecondstar");
  var intheshadowsThirdStar = document.getElementById("intheshadowsthirdstar");
  var intheshadowsFourthStar = document.getElementById("intheshadowsfourthstar");
  var intheshadowsFifthStar = document.getElementById("intheshadowsfifthstar");
  var maskFirstStar = document.getElementById("maskfirststar");
  var maskSecondStar = document.getElementById("masksecondstar");
  var maskThirdStar = document.getElementById("maskthirdstar");
  var maskFourthStar = document.getElementById("maskfourthstar");
  var maskFifthStar = document.getElementById("maskfifthstar");
  var moneyainttheanswerFirstStar = document.getElementById("moneyainttheanswerfirststar");
  var moneyainttheanswerSecondStar = document.getElementById("moneyainttheanswersecondstar");
  var moneyainttheanswerThirdStar = document.getElementById("moneyainttheanswerthirdstar");
  var moneyainttheanswerFourthStar = document.getElementById("moneyainttheanswerfourthstar");
  var moneyainttheanswerFifthStar = document.getElementById("moneyainttheanswerfifthstar");
  var fakefriendsFirstStar = document.getElementById("fakefriendsfirststar");
  var fakefriendsSecondStar = document.getElementById("fakefriendssecondstar");
  var fakefriendsThirdStar = document.getElementById("fakefriendsthirdstar");
  var fakefriendsFourthStar = document.getElementById("fakefriendsfourthstar");
  var fakefriendsFifthStar = document.getElementById("fakefriendsfifthstar");
  if (starId == "lapsfirststar") {
    lapsFirstStar.innerText = "★";
    lapsFirstStar.classList.remove("emptystar");
    lapsFirstStar.classList.add("filledstar");
    lapsSecondStar.innerText = "☆";
    lapsSecondStar.classList.remove("filledstar");
    lapsSecondStar.classList.add("emptystar");
    lapsThirdStar.innerText = "☆";
    lapsThirdStar.classList.remove("filledstar");
    lapsThirdStar.classList.add("emptystar");
    lapsFourthStar.innerText = "☆";
    lapsFourthStar.classList.remove("filledstar");
    lapsFourthStar.classList.add("emptystar");
    lapsFifthStar.innerText = "☆";
    lapsFifthStar.classList.remove("filledstar");
    lapsFifthStar.classList.add("emptystar");
  } else if (starId == "lapssecondstar") {
    lapsFirstStar.innerText = "★";
    lapsFirstStar.classList.remove("emptystar");
    lapsFirstStar.classList.add("filledstar");
    lapsSecondStar.innerText = "★";
    lapsSecondStar.classList.remove("emptystar");
    lapsSecondStar.classList.add("filledstar");
    lapsThirdStar.innerText = "☆";
    lapsThirdStar.classList.remove("filledstar");
    lapsThirdStar.classList.add("emptystar");
    lapsFourthStar.innerText = "☆";
    lapsFourthStar.classList.remove("filledstar");
    lapsFourthStar.classList.add("emptystar");
    lapsFifthStar.innerText = "☆";
    lapsFifthStar.classList.remove("filledstar");
    lapsFifthStar.classList.add("emptystar");
  } else if (starId == "lapsthirdstar") {
    lapsFirstStar.innerText = "★";
    lapsFirstStar.classList.remove("emptystar");
    lapsFirstStar.classList.add("filledstar");
    lapsSecondStar.innerText = "★";
    lapsSecondStar.classList.remove("emptystar");
    lapsSecondStar.classList.add("filledstar");
    lapsThirdStar.innerText = "★";
    lapsThirdStar.classList.remove("emptystar");
    lapsThirdStar.classList.add("filledstar");
    lapsFourthStar.innerText = "☆";
    lapsFourthStar.classList.remove("filledstar");
    lapsFourthStar.classList.add("emptystar");
    lapsFifthStar.innerText = "☆";
    lapsFifthStar.classList.remove("filledstar");
    lapsFifthStar.classList.add("emptystar");
  } else if (starId == "lapsfourthstar") {
    lapsFirstStar.innerText = "★";
    lapsFirstStar.classList.remove("emptystar");
    lapsFirstStar.classList.add("filledstar");
    lapsSecondStar.innerText = "★";
    lapsSecondStar.classList.remove("emptystar");
    lapsSecondStar.classList.add("filledstar");
    lapsThirdStar.innerText = "★";
    lapsThirdStar.classList.remove("emptystar");
    lapsThirdStar.classList.add("filledstar");
    lapsFourthStar.innerText = "★";
    lapsFourthStar.classList.remove("emptystar");
    lapsFourthStar.classList.add("filledstar");
    lapsFifthStar.innerText = "☆";
    lapsFifthStar.classList.remove("filledstar");
    lapsFifthStar.classList.add("emptystar");
  } else if (starId == "lapsfifthstar") {
    lapsFirstStar.innerText = "★";
    lapsFirstStar.classList.remove("emptystar");
    lapsFirstStar.classList.add("filledstar");
    lapsSecondStar.innerText = "★";
    lapsSecondStar.classList.remove("emptystar");
    lapsSecondStar.classList.add("filledstar");
    lapsThirdStar.innerText = "★";
    lapsThirdStar.classList.remove("emptystar");
    lapsThirdStar.classList.add("filledstar");
    lapsFourthStar.innerText = "★";
    lapsFourthStar.classList.remove("emptystar");
    lapsFourthStar.classList.add("filledstar");
    lapsFifthStar.innerText = "★";
    lapsFifthStar.classList.remove("emptystar");
    lapsFifthStar.classList.add("filledstar");
  } else if (starId == "unstoppablefirststar") {
    unstoppableFirstStar.innerText = "★";
    unstoppableFirstStar.classList.remove("emptystar");
    unstoppableFirstStar.classList.add("filledstar");
    unstoppableSecondStar.innerText = "☆";
    unstoppableSecondStar.classList.remove("filledstar");
    unstoppableSecondStar.classList.add("emptystar");
    unstoppableThirdStar.innerText = "☆";
    unstoppableThirdStar.classList.remove("filledstar");
    unstoppableThirdStar.classList.add("emptystar");
    unstoppableFourthStar.innerText = "☆";
    unstoppableFourthStar.classList.remove("filledstar");
    unstoppableFourthStar.classList.add("emptystar");
    unstoppableFifthStar.innerText = "☆";
    unstoppableFifthStar.classList.remove("filledstar");
    unstoppableFifthStar.classList.add("emptystar");
  } else if (starId == "unstoppablesecondstar") {
    unstoppableFirstStar.innerText = "★";
    unstoppableFirstStar.classList.remove("emptystar");
    unstoppableFirstStar.classList.add("filledstar");
    unstoppableSecondStar.innerText = "★";
    unstoppableSecondStar.classList.remove("emptystar");
    unstoppableSecondStar.classList.add("filledstar");
    unstoppableThirdStar.innerText = "☆";
    unstoppableThirdStar.classList.remove("filledstar");
    unstoppableThirdStar.classList.add("emptystar");
    unstoppableFourthStar.innerText = "☆";
    unstoppableFourthStar.classList.remove("filledstar");
    unstoppableFourthStar.classList.add("emptystar");
    unstoppableFifthStar.innerText = "☆";
    unstoppableFifthStar.classList.remove("filledstar");
    unstoppableFifthStar.classList.add("emptystar");
  } else if (starId == "unstoppablethirdstar") {
    unstoppableFirstStar.innerText = "★";
    unstoppableFirstStar.classList.remove("emptystar");
    unstoppableFirstStar.classList.add("filledstar");
    unstoppableSecondStar.innerText = "★";
    unstoppableSecondStar.classList.remove("emptystar");
    unstoppableSecondStar.classList.add("filledstar");
    unstoppableThirdStar.innerText = "★";
    unstoppableThirdStar.classList.remove("emptystar");
    unstoppableThirdStar.classList.add("filledstar");
    unstoppableFourthStar.innerText = "☆";
    unstoppableFourthStar.classList.remove("filledstar");
    unstoppableFourthStar.classList.add("emptystar");
    unstoppableFifthStar.innerText = "☆";
    unstoppableFifthStar.classList.remove("filledstar");
    unstoppableFifthStar.classList.add("emptystar");
  } else if (starId == "unstoppablefourthstar") {
    unstoppableFirstStar.innerText = "★";
    unstoppableFirstStar.classList.remove("emptystar");
    unstoppableFirstStar.classList.add("filledstar");
    unstoppableSecondStar.innerText = "★";
    unstoppableSecondStar.classList.remove("emptystar");
    unstoppableSecondStar.classList.add("filledstar");
    unstoppableThirdStar.innerText = "★";
    unstoppableThirdStar.classList.remove("emptystar");
    unstoppableThirdStar.classList.add("filledstar");
    unstoppableFourthStar.innerText = "★";
    unstoppableFourthStar.classList.remove("emptystar");
    unstoppableFourthStar.classList.add("filledstar");
    unstoppableFifthStar.innerText = "☆";
    unstoppableFifthStar.classList.remove("filledstar");
    unstoppableFifthStar.classList.add("emptystar");
  } else if (starId == "unstoppablefifthstar") {
    unstoppableFirstStar.innerText = "★";
    unstoppableFirstStar.classList.remove("emptystar");
    unstoppableFirstStar.classList.add("filledstar");
    unstoppableSecondStar.innerText = "★";
    unstoppableSecondStar.classList.remove("emptystar");
    unstoppableSecondStar.classList.add("filledstar");
    unstoppableThirdStar.innerText = "★";
    unstoppableThirdStar.classList.remove("emptystar");
    unstoppableThirdStar.classList.add("filledstar");
    unstoppableFourthStar.innerText = "★";
    unstoppableFourthStar.classList.remove("emptystar");
    unstoppableFourthStar.classList.add("filledstar");
    unstoppableFifthStar.innerText = "★";
    unstoppableFifthStar.classList.remove("emptystar");
    unstoppableFifthStar.classList.add("filledstar");
  } else if (starId == "stolemyheartfirststar") {
    stolemyheartFirstStar.innerText = "★";
    stolemyheartFirstStar.classList.remove("emptystar");
    stolemyheartFirstStar.classList.add("filledstar");
    stolemyheartSecondStar.innerText = "☆";
    stolemyheartSecondStar.classList.remove("filledstar");
    stolemyheartSecondStar.classList.add("emptystar");
    stolemyheartThirdStar.innerText = "☆";
    stolemyheartThirdStar.classList.remove("filledstar");
    stolemyheartThirdStar.classList.add("emptystar");
    stolemyheartFourthStar.innerText = "☆";
    stolemyheartFourthStar.classList.remove("filledstar");
    stolemyheartFourthStar.classList.add("emptystar");
    stolemyheartFifthStar.innerText = "☆";
    stolemyheartFifthStar.classList.remove("filledstar");
    stolemyheartFifthStar.classList.add("emptystar");
  } else if (starId == "stolemyheartsecondstar") {
    stolemyheartFirstStar.innerText = "★";
    stolemyheartFirstStar.classList.remove("emptystar");
    stolemyheartFirstStar.classList.add("filledstar");
    stolemyheartSecondStar.innerText = "★";
    stolemyheartSecondStar.classList.remove("emptystar");
    stolemyheartSecondStar.classList.add("filledstar");
    stolemyheartThirdStar.innerText = "☆";
    stolemyheartThirdStar.classList.remove("filledstar");
    stolemyheartThirdStar.classList.add("emptystar");
    stolemyheartFourthStar.innerText = "☆";
    stolemyheartFourthStar.classList.remove("filledstar");
    stolemyheartFourthStar.classList.add("emptystar");
    stolemyheartFifthStar.innerText = "☆";
    stolemyheartFifthStar.classList.remove("filledstar");
    stolemyheartFifthStar.classList.add("emptystar");
  } else if (starId == "stolemyheartthirdstar") {
    stolemyheartFirstStar.innerText = "★";
    stolemyheartFirstStar.classList.remove("emptystar");
    stolemyheartFirstStar.classList.add("filledstar");
    stolemyheartSecondStar.innerText = "★";
    stolemyheartSecondStar.classList.remove("emptystar");
    stolemyheartSecondStar.classList.add("filledstar");
    stolemyheartThirdStar.innerText = "★";
    stolemyheartThirdStar.classList.remove("emptystar");
    stolemyheartThirdStar.classList.add("filledstar");
    stolemyheartFourthStar.innerText = "☆";
    stolemyheartFourthStar.classList.remove("filledstar");
    stolemyheartFourthStar.classList.add("emptystar");
    stolemyheartFifthStar.innerText = "☆";
    stolemyheartFifthStar.classList.remove("filledstar");
    stolemyheartFifthStar.classList.add("emptystar");
  } else if (starId == "stolemyheartfourthstar") {
    stolemyheartFirstStar.innerText = "★";
    stolemyheartFirstStar.classList.remove("emptystar");
    stolemyheartFirstStar.classList.add("filledstar");
    stolemyheartSecondStar.innerText = "★";
    stolemyheartSecondStar.classList.remove("emptystar");
    stolemyheartSecondStar.classList.add("filledstar");
    stolemyheartThirdStar.innerText = "★";
    stolemyheartThirdStar.classList.remove("emptystar");
    stolemyheartThirdStar.classList.add("filledstar");
    stolemyheartFourthStar.innerText = "★";
    stolemyheartFourthStar.classList.remove("emptystar");
    stolemyheartFourthStar.classList.add("filledstar");
    stolemyheartFifthStar.innerText = "☆";
    stolemyheartFifthStar.classList.remove("filledstar");
    stolemyheartFifthStar.classList.add("emptystar");
  } else if (starId == "stolemyheartfifthstar") {
    stolemyheartFirstStar.innerText = "★";
    stolemyheartFirstStar.classList.remove("emptystar");
    stolemyheartFirstStar.classList.add("filledstar");
    stolemyheartSecondStar.innerText = "★";
    stolemyheartSecondStar.classList.remove("emptystar");
    stolemyheartSecondStar.classList.add("filledstar");
    stolemyheartThirdStar.innerText = "★";
    stolemyheartThirdStar.classList.remove("emptystar");
    stolemyheartThirdStar.classList.add("filledstar");
    stolemyheartFourthStar.innerText = "★";
    stolemyheartFourthStar.classList.remove("emptystar");
    stolemyheartFourthStar.classList.add("filledstar");
    stolemyheartFifthStar.innerText = "★";
    stolemyheartFifthStar.classList.remove("emptystar");
    stolemyheartFifthStar.classList.add("filledstar");
  } else if (starId == "intheshadowsfirststar") {
    intheshadowsFirstStar.innerText = "★";
    intheshadowsFirstStar.classList.remove("emptystar");
    intheshadowsFirstStar.classList.add("filledstar");
    intheshadowsSecondStar.innerText = "☆";
    intheshadowsSecondStar.classList.remove("filledstar");
    intheshadowsSecondStar.classList.add("emptystar");
    intheshadowsThirdStar.innerText = "☆";
    intheshadowsThirdStar.classList.remove("filledstar");
    intheshadowsThirdStar.classList.add("emptystar");
    intheshadowsFourthStar.innerText = "☆";
    intheshadowsFourthStar.classList.remove("filledstar");
    intheshadowsFourthStar.classList.add("emptystar");
    intheshadowsFifthStar.innerText = "☆";
    intheshadowsFifthStar.classList.remove("filledstar");
    intheshadowsFifthStar.classList.add("emptystar");
  } else if (starId == "intheshadowssecondstar") {
    intheshadowsFirstStar.innerText = "★";
    intheshadowsFirstStar.classList.remove("emptystar");
    intheshadowsFirstStar.classList.add("filledstar");
    intheshadowsSecondStar.innerText = "★";
    intheshadowsSecondStar.classList.remove("emptystar");
    intheshadowsSecondStar.classList.add("filledstar");
    intheshadowsThirdStar.innerText = "☆";
    intheshadowsThirdStar.classList.remove("filledstar");
    intheshadowsThirdStar.classList.add("emptystar");
    intheshadowsFourthStar.innerText = "☆";
    intheshadowsFourthStar.classList.remove("filledstar");
    intheshadowsFourthStar.classList.add("emptystar");
    intheshadowsFifthStar.innerText = "☆";
    intheshadowsFifthStar.classList.remove("filledstar");
    intheshadowsFifthStar.classList.add("emptystar");
  } else if (starId == "intheshadowsthirdstar") {
    intheshadowsFirstStar.innerText = "★";
    intheshadowsFirstStar.classList.remove("emptystar");
    intheshadowsFirstStar.classList.add("filledstar");
    intheshadowsSecondStar.innerText = "★";
    intheshadowsSecondStar.classList.remove("emptystar");
    intheshadowsSecondStar.classList.add("filledstar");
    intheshadowsThirdStar.innerText = "★";
    intheshadowsThirdStar.classList.remove("emptystar");
    intheshadowsThirdStar.classList.add("filledstar");
    intheshadowsFourthStar.innerText = "☆";
    intheshadowsFourthStar.classList.remove("filledstar");
    intheshadowsFourthStar.classList.add("emptystar");
    intheshadowsFifthStar.innerText = "☆";
    intheshadowsFifthStar.classList.remove("filledstar");
    intheshadowsFifthStar.classList.add("emptystar");
  } else if (starId == "intheshadowsfourthstar") {
    intheshadowsFirstStar.innerText = "★";
    intheshadowsFirstStar.classList.remove("emptystar");
    intheshadowsFirstStar.classList.add("filledstar");
    intheshadowsSecondStar.innerText = "★";
    intheshadowsSecondStar.classList.remove("emptystar");
    intheshadowsSecondStar.classList.add("filledstar");
    intheshadowsThirdStar.innerText = "★";
    intheshadowsThirdStar.classList.remove("emptystar");
    intheshadowsThirdStar.classList.add("filledstar");
    intheshadowsFourthStar.innerText = "★";
    intheshadowsFourthStar.classList.remove("emptystar");
    intheshadowsFourthStar.classList.add("filledstar");
    intheshadowsFifthStar.innerText = "☆";
    intheshadowsFifthStar.classList.remove("filledstar");
    intheshadowsFifthStar.classList.add("emptystar");
  } else if (starId == "intheshadowsfifthstar") {
    intheshadowsFirstStar.innerText = "★";
    intheshadowsFirstStar.classList.remove("emptystar");
    intheshadowsFirstStar.classList.add("filledstar");
    intheshadowsSecondStar.innerText = "★";
    intheshadowsSecondStar.classList.remove("emptystar");
    intheshadowsSecondStar.classList.add("filledstar");
    intheshadowsThirdStar.innerText = "★";
    intheshadowsThirdStar.classList.remove("emptystar");
    intheshadowsThirdStar.classList.add("filledstar");
    intheshadowsFourthStar.innerText = "★";
    intheshadowsFourthStar.classList.remove("emptystar");
    intheshadowsFourthStar.classList.add("filledstar");
    intheshadowsFifthStar.innerText = "★";
    intheshadowsFifthStar.classList.remove("emptystar");
    intheshadowsFifthStar.classList.add("filledstar");
  } else if (starId == "maskfirststar") {
    maskFirstStar.innerText = "★";
    maskFirstStar.classList.remove("emptystar");
    maskFirstStar.classList.add("filledstar");
    maskSecondStar.innerText = "☆";
    maskSecondStar.classList.remove("filledstar");
    maskSecondStar.classList.add("emptystar");
    maskThirdStar.innerText = "☆";
    maskThirdStar.classList.remove("filledstar");
    maskThirdStar.classList.add("emptystar");
    maskFourthStar.innerText = "☆";
    maskFourthStar.classList.remove("filledstar");
    maskFourthStar.classList.add("emptystar");
    maskFifthStar.innerText = "☆";
    maskFifthStar.classList.remove("filledstar");
    maskFifthStar.classList.add("emptystar");
  } else if (starId == "masksecondstar") {
    maskFirstStar.innerText = "★";
    maskFirstStar.classList.remove("emptystar");
    maskFirstStar.classList.add("filledstar");
    maskSecondStar.innerText = "★";
    maskSecondStar.classList.remove("emptystar");
    maskSecondStar.classList.add("filledstar");
    maskThirdStar.innerText = "☆";
    maskThirdStar.classList.remove("filledstar");
    maskThirdStar.classList.add("emptystar");
    maskFourthStar.innerText = "☆";
    maskFourthStar.classList.remove("filledstar");
    maskFourthStar.classList.add("emptystar");
    maskFifthStar.innerText = "☆";
    maskFifthStar.classList.remove("filledstar");
    maskFifthStar.classList.add("emptystar");
  } else if (starId == "maskthirdstar") {
    maskFirstStar.innerText = "★";
    maskFirstStar.classList.remove("emptystar");
    maskFirstStar.classList.add("filledstar");
    maskSecondStar.innerText = "★";
    maskSecondStar.classList.remove("emptystar");
    maskSecondStar.classList.add("filledstar");
    maskThirdStar.innerText = "★";
    maskThirdStar.classList.remove("emptystar");
    maskThirdStar.classList.add("filledstar");
    maskFourthStar.innerText = "☆";
    maskFourthStar.classList.remove("filledstar");
    maskFourthStar.classList.add("emptystar");
    maskFifthStar.innerText = "☆";
    maskFifthStar.classList.remove("filledstar");
    maskFifthStar.classList.add("emptystar");
  } else if (starId == "maskfourthstar") {
    maskFirstStar.innerText = "★";
    maskFirstStar.classList.remove("emptystar");
    maskFirstStar.classList.add("filledstar");
    maskSecondStar.innerText = "★";
    maskSecondStar.classList.remove("emptystar");
    maskSecondStar.classList.add("filledstar");
    maskThirdStar.innerText = "★";
    maskThirdStar.classList.remove("emptystar");
    maskThirdStar.classList.add("filledstar");
    maskFourthStar.innerText = "★";
    maskFourthStar.classList.remove("emptystar");
    maskFourthStar.classList.add("filledstar");
    maskFifthStar.innerText = "☆";
    maskFifthStar.classList.remove("filledstar");
    maskFifthStar.classList.add("emptystar");
  } else if (starId == "maskfifthstar") {
    maskFirstStar.innerText = "★";
    maskFirstStar.classList.remove("emptystar");
    maskFirstStar.classList.add("filledstar");
    maskSecondStar.innerText = "★";
    maskSecondStar.classList.remove("emptystar");
    maskSecondStar.classList.add("filledstar");
    maskThirdStar.innerText = "★";
    maskThirdStar.classList.remove("emptystar");
    maskThirdStar.classList.add("filledstar");
    maskFourthStar.innerText = "★";
    maskFourthStar.classList.remove("emptystar");
    maskFourthStar.classList.add("filledstar");
    maskFifthStar.innerText = "★";
    maskFifthStar.classList.remove("emptystar");
    maskFifthStar.classList.add("filledstar");
  } else if (starId == "moneyainttheanswerfirststar") {
    moneyainttheanswerFirstStar.innerText = "★";
    moneyainttheanswerFirstStar.classList.remove("emptystar");
    moneyainttheanswerFirstStar.classList.add("filledstar");
    moneyainttheanswerSecondStar.innerText = "☆";
    moneyainttheanswerSecondStar.classList.remove("filledstar");
    moneyainttheanswerSecondStar.classList.add("emptystar");
    moneyainttheanswerThirdStar.innerText = "☆";
    moneyainttheanswerThirdStar.classList.remove("filledstar");
    moneyainttheanswerThirdStar.classList.add("emptystar");
    moneyainttheanswerFourthStar.innerText = "☆";
    moneyainttheanswerFourthStar.classList.remove("filledstar");
    moneyainttheanswerFourthStar.classList.add("emptystar");
    moneyainttheanswerFifthStar.innerText = "☆";
    moneyainttheanswerFifthStar.classList.remove("filledstar");
    moneyainttheanswerFifthStar.classList.add("emptystar");
  } else if (starId == "moneyainttheanswersecondstar") {
    moneyainttheanswerFirstStar.innerText = "★";
    moneyainttheanswerFirstStar.classList.remove("emptystar");
    moneyainttheanswerFirstStar.classList.add("filledstar");
    moneyainttheanswerSecondStar.innerText = "★";
    moneyainttheanswerSecondStar.classList.remove("emptystar");
    moneyainttheanswerSecondStar.classList.add("filledstar");
    moneyainttheanswerThirdStar.innerText = "☆";
    moneyainttheanswerThirdStar.classList.remove("filledstar");
    moneyainttheanswerThirdStar.classList.add("emptystar");
    moneyainttheanswerFourthStar.innerText = "☆";
    moneyainttheanswerFourthStar.classList.remove("filledstar");
    moneyainttheanswerFourthStar.classList.add("emptystar");
    moneyainttheanswerFifthStar.innerText = "☆";
    moneyainttheanswerFifthStar.classList.remove("filledstar");
    moneyainttheanswerFifthStar.classList.add("emptystar");
  } else if (starId == "moneyainttheanswerthirdstar") {
    moneyainttheanswerFirstStar.innerText = "★";
    moneyainttheanswerFirstStar.classList.remove("emptystar");
    moneyainttheanswerFirstStar.classList.add("filledstar");
    moneyainttheanswerSecondStar.innerText = "★";
    moneyainttheanswerSecondStar.classList.remove("emptystar");
    moneyainttheanswerSecondStar.classList.add("filledstar");
    moneyainttheanswerThirdStar.innerText = "★";
    moneyainttheanswerThirdStar.classList.remove("emptystar");
    moneyainttheanswerThirdStar.classList.add("filledstar");
    moneyainttheanswerFourthStar.innerText = "☆";
    moneyainttheanswerFourthStar.classList.remove("filledstar");
    moneyainttheanswerFourthStar.classList.add("emptystar");
    moneyainttheanswerFifthStar.innerText = "☆";
    moneyainttheanswerFifthStar.classList.remove("filledstar");
    moneyainttheanswerFifthStar.classList.add("emptystar");
  } else if (starId == "moneyainttheanswerfourthstar") {
    moneyainttheanswerFirstStar.innerText = "★";
    moneyainttheanswerFirstStar.classList.remove("emptystar");
    moneyainttheanswerFirstStar.classList.add("filledstar");
    moneyainttheanswerSecondStar.innerText = "★";
    moneyainttheanswerSecondStar.classList.remove("emptystar");
    moneyainttheanswerSecondStar.classList.add("filledstar");
    moneyainttheanswerThirdStar.innerText = "★";
    moneyainttheanswerThirdStar.classList.remove("emptystar");
    moneyainttheanswerThirdStar.classList.add("filledstar");
    moneyainttheanswerFourthStar.innerText = "★";
    moneyainttheanswerFourthStar.classList.remove("emptystar");
    moneyainttheanswerFourthStar.classList.add("filledstar");
    moneyainttheanswerFifthStar.innerText = "☆";
    moneyainttheanswerFifthStar.classList.remove("filledstar");
    moneyainttheanswerFifthStar.classList.add("emptystar");
  } else if (starId == "moneyainttheanswerfifthstar") {
    moneyainttheanswerFirstStar.innerText = "★";
    moneyainttheanswerFirstStar.classList.remove("emptystar");
    moneyainttheanswerFirstStar.classList.add("filledstar");
    moneyainttheanswerSecondStar.innerText = "★";
    moneyainttheanswerSecondStar.classList.remove("emptystar");
    moneyainttheanswerSecondStar.classList.add("filledstar");
    moneyainttheanswerThirdStar.innerText = "★";
    moneyainttheanswerThirdStar.classList.remove("emptystar");
    moneyainttheanswerThirdStar.classList.add("filledstar");
    moneyainttheanswerFourthStar.innerText = "★";
    moneyainttheanswerFourthStar.classList.remove("emptystar");
    moneyainttheanswerFourthStar.classList.add("filledstar");
    moneyainttheanswerFifthStar.innerText = "★";
    moneyainttheanswerFifthStar.classList.remove("emptystar");
    moneyainttheanswerFifthStar.classList.add("filledstar");
  } else if (starId == "fakefriendsfirststar") {
    fakefriendsFirstStar.innerText = "★";
    fakefriendsFirstStar.classList.remove("emptystar");
    fakefriendsFirstStar.classList.add("filledstar");
    fakefriendsSecondStar.innerText = "☆";
    fakefriendsSecondStar.classList.remove("filledstar");
    fakefriendsSecondStar.classList.add("emptystar");
    fakefriendsThirdStar.innerText = "☆";
    fakefriendsThirdStar.classList.remove("filledstar");
    fakefriendsThirdStar.classList.add("emptystar");
    fakefriendsFourthStar.innerText = "☆";
    fakefriendsFourthStar.classList.remove("filledstar");
    fakefriendsFourthStar.classList.add("emptystar");
    fakefriendsFifthStar.innerText = "☆";
    fakefriendsFifthStar.classList.remove("filledstar");
    fakefriendsFifthStar.classList.add("emptystar");
  } else if (starId == "fakefriendssecondstar") {
    fakefriendsFirstStar.innerText = "★";
    fakefriendsFirstStar.classList.remove("emptystar");
    fakefriendsFirstStar.classList.add("filledstar");
    fakefriendsSecondStar.innerText = "★";
    fakefriendsSecondStar.classList.remove("emptystar");
    fakefriendsSecondStar.classList.add("filledstar");
    fakefriendsThirdStar.innerText = "☆";
    fakefriendsThirdStar.classList.remove("filledstar");
    fakefriendsThirdStar.classList.add("emptystar");
    fakefriendsFourthStar.innerText = "☆";
    fakefriendsFourthStar.classList.remove("filledstar");
    fakefriendsFourthStar.classList.add("emptystar");
    fakefriendsFifthStar.innerText = "☆";
    fakefriendsFifthStar.classList.remove("filledstar");
    fakefriendsFifthStar.classList.add("emptystar");
  } else if (starId == "fakefriendsthirdstar") {
    fakefriendsFirstStar.innerText = "★";
    fakefriendsFirstStar.classList.remove("emptystar");
    fakefriendsFirstStar.classList.add("filledstar");
    fakefriendsSecondStar.innerText = "★";
    fakefriendsSecondStar.classList.remove("emptystar");
    fakefriendsSecondStar.classList.add("filledstar");
    fakefriendsThirdStar.innerText = "★";
    fakefriendsThirdStar.classList.remove("emptystar");
    fakefriendsThirdStar.classList.add("filledstar");
    fakefriendsFourthStar.innerText = "☆";
    fakefriendsFourthStar.classList.remove("filledstar");
    fakefriendsFourthStar.classList.add("emptystar");
    fakefriendsFifthStar.innerText = "☆";
    fakefriendsFifthStar.classList.remove("filledstar");
    fakefriendsFifthStar.classList.add("emptystar");
  } else if (starId == "fakefriendsfourthstar") {
    fakefriendsFirstStar.innerText = "★";
    fakefriendsFirstStar.classList.remove("emptystar");
    fakefriendsFirstStar.classList.add("filledstar");
    fakefriendsSecondStar.innerText = "★";
    fakefriendsSecondStar.classList.remove("emptystar");
    fakefriendsSecondStar.classList.add("filledstar");
    fakefriendsThirdStar.innerText = "★";
    fakefriendsThirdStar.classList.remove("emptystar");
    fakefriendsThirdStar.classList.add("filledstar");
    fakefriendsFourthStar.innerText = "★";
    fakefriendsFourthStar.classList.remove("emptystar");
    fakefriendsFourthStar.classList.add("filledstar");
    fakefriendsFifthStar.innerText = "☆";
    fakefriendsFifthStar.classList.remove("filledstar");
    fakefriendsFifthStar.classList.add("emptystar");
  } else if (starId == "fakefriendsfifthstar") {
    fakefriendsFirstStar.innerText = "★";
    fakefriendsFirstStar.classList.remove("emptystar");
    fakefriendsFirstStar.classList.add("filledstar");
    fakefriendsSecondStar.innerText = "★";
    fakefriendsSecondStar.classList.remove("emptystar");
    fakefriendsSecondStar.classList.add("filledstar");
    fakefriendsThirdStar.innerText = "★";
    fakefriendsThirdStar.classList.remove("emptystar");
    fakefriendsThirdStar.classList.add("filledstar");
    fakefriendsFourthStar.innerText = "★";
    fakefriendsFourthStar.classList.remove("emptystar");
    fakefriendsFourthStar.classList.add("filledstar");
    fakefriendsFifthStar.innerText = "★";
    fakefriendsFifthStar.classList.remove("emptystar");
    fakefriendsFifthStar.classList.add("filledstar");
  }
}